# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI with Gradle

on:
  push:
    branches:
      - "master"
      - "*.x"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/android.yml"
  pull_request:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/android.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: thyrlian/android-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare the source for build
        run: chmod +x gradlew

      - name: Build APK with Gradle
        run: ./gradlew assembleDebug --no-daemon
