# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI with Gradle

on:
  push:
    branches:
      - 'master'
      - '*.x'
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/android.yml'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/android.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /opt/android-sdk
      ANDROID_SDK_VERSION: 9477386
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"
          cache: 'gradle'

#      - name: Install tools
#        run: sudo apt-get update -q && sudo apt-get install unzip wget -y -q

      - name: Download Android SDK
        uses: wei/wget@v1
        with:
          args: -q https://dl.google.com/android/repository/commandlinetools-linux-${{ env.ANDROID_SDK_ROOT }}_latest.zip

      - name: Setup Android SDK
        run: mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest && \
            unzip *tools*linux*.zip -d ${ANDROID_SDK_ROOT}/cmdline-tools/ && \
            mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest && \
            rm *tools*linux*.zip && \
            export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin

      - name: Install SDK tools
        run: (while sleep 3; do echo "y"; done) | sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.2" --channel=0

      - name: Prepare the source for build
        run: chmod +x gradlew

      - name: Build APK with Gradle
        run: ./gradlew assembleDebug --no-daemon
